@Host= https://localhost:7133

POST {{Host}}/auth/register
Content-Type: application/json

{
    "firstname" : "Vivek",
    "lastname" : "Verma",
    "email" : "vivek@verma.com",
    "password" : "Vivek@Verma"
}